# Generated by Django 5.0 on 2023-12-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexxus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
